# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ae60335e69dc86e5c137a5ac7777a68f"
name = "node-vue-app"
handle = "node-vue-app-1"
application_url = "https://redesigned-goldfish-4jq5jxxqqwqcj4j6-4040.app.github.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "carrierteststore.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,write_products"

[auth]
redirect_urls = [
  "https://redesigned-goldfish-4jq5jxxqqwqcj4j6-4040.app.github.dev/auth/callback",
  "https://redesigned-goldfish-4jq5jxxqqwqcj4j6-4040.app.github.dev/auth/shopify/callback",
  "https://redesigned-goldfish-4jq5jxxqqwqcj4j6-4040.app.github.dev/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
